spring:
  datasource:
   url: jdbc:postgresql://localhost:5432/jwt_security_db
   username: postgres
   password: 1234
   
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
